In [16]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [17]:
df = pd.read_excel("123.xlsx")

In [18]:
df.head()

    縣市           牛乳          牛肉   乳牛數量  肉牛數量  用地面積
0  新北市   117502.880   32420.171    691   605     3
1  台北市     4956.965     299.277     34     2     0
2  桃園市   461974.797   62723.334   2662   945    28
3  台中市   246454.775   43451.531   1629  1317    10
4  台南市  2069661.489  625846.666  11850  3935   120

In [19]:
df.乳牛數量.mean()

3442.6111111111113

In [20]:
df.乳牛數量.std()

4566.776429552507

In [21]:
df.describe()

                 牛乳             牛肉          乳牛數量         肉牛數量        用地面積
count  1.800000e+01      18.000000     18.000000    18.000000   18.000000
mean   6.096764e+05  136688.099222   3442.611111  1855.944444   34.000000
std    8.241837e+05  191354.508055   4566.776430  2193.860912   36.569032
min    3.994825e+03     299.277000     34.000000     0.000000    0.000000
25%    8.661442e+04   24741.983250    495.750000   453.000000    6.000000
50%    1.997043e+05   53343.088000   1082.500000  1002.500000   21.000000
75%    6.707938e+05  109926.932500   4186.000000  2606.750000   49.000000
max    2.694994e+06  625846.666000  14704.000000  7825.000000  120.000000

In [22]:
df.corr()

            牛乳        牛肉      乳牛數量      肉牛數量      用地面積
牛乳    1.000000  0.903533  0.998552  0.584343  0.799097
牛肉    0.903533  1.000000  0.901463  0.665951  0.828519
乳牛數量  0.998552  0.901463  1.000000  0.589451  0.802183
肉牛數量  0.584343  0.665951  0.589451  1.000000  0.656731
用地面積  0.799097  0.828519  0.802183  0.656731  1.000000

In [23]:
df.乳牛數量.corr(df.肉牛數量)

0.589450991405131

In [24]:
df["加總"] = df[["牛乳", "牛肉", "乳牛數量", "肉牛數量", "用地面積"]].sum(1)

In [25]:
df.head()

    縣市           牛乳          牛肉   乳牛數量  肉牛數量  用地面積           加總
0  新北市   117502.880   32420.171    691   605     3   151222.051
1  台北市     4956.965     299.277     34     2     0     5292.242
2  桃園市   461974.797   62723.334   2662   945    28   528333.131
3  台中市   246454.775   43451.531   1629  1317    10   292862.306
4  台南市  2069661.489  625846.666  11850  3935   120  2711413.155

In [26]:
df["熱量"] = df["牛乳"]*0.5 + df["牛肉"]*1.5

In [27]:
df

     縣市           牛乳          牛肉   乳牛數量  肉牛數量  用地面積           加總            熱量
0   新北市   117502.880   32420.171    691   605     3   151222.051  1.073817e+05
1   台北市     4956.965     299.277     34     2     0     5292.242  2.927398e+03
2   桃園市   461974.797   62723.334   2662   945    28   528333.131  3.250724e+05
3   台中市   246454.775   43451.531   1629  1317    10   292862.306  1.884047e+05
4   台南市  2069661.489  625846.666  11850  3935   120  2711413.155  1.973601e+06
5   高雄市   632887.771   96288.631   3616   860    22   733674.402  4.608768e+05
6   新竹縣   203520.007   27137.016    958   425    13   232053.023  1.424655e+05
7   苗栗縣   195888.627   23943.639   1191   537     9   221569.266  1.338598e+05
8   彰化縣  2694993.796  373878.163  14704  2817    90  3086482.959  1.908314e+06
9   南投縣    76767.026    3434.696    452    11     3    80667.722  4.353556e+04
10  雲林縣  1388168.494  474524.567   7147  3702    54  1873596.061  1.405871e+06
11  嘉義縣   683429.133  114473.033   4376  1060    32   803370.166  5.134241e+05
12  屏東縣  1864768.812  402308.784  10666  7825    76  2285644.596  1.535848e+06
13  台東縣   116156.593   49194.170    627  1522    20   167519.763  1.318696e+05
14  花蓮縣   178730.894   62519.391    974  1976    90   244290.285  1.831445e+05
15  新竹市    27819.861    9271.225    240    44     5    37380.086  2.781677e+04
16  嘉義市     3994.825    1179.486     36     0     3     5213.311  3.766642e+03
17  金門縣     6498.299   57492.006    114  5824    34    69962.305  8.948716e+04

In [28]:
df.sort_values(by="乳牛數量", ascending=False).head(10)

     縣市           牛乳          牛肉   乳牛數量  肉牛數量  用地面積           加總            熱量
8   彰化縣  2694993.796  373878.163  14704  2817    90  3086482.959  1.908314e+06
4   台南市  2069661.489  625846.666  11850  3935   120  2711413.155  1.973601e+06
12  屏東縣  1864768.812  402308.784  10666  7825    76  2285644.596  1.535848e+06
10  雲林縣  1388168.494  474524.567   7147  3702    54  1873596.061  1.405871e+06
11  嘉義縣   683429.133  114473.033   4376  1060    32   803370.166  5.134241e+05
5   高雄市   632887.771   96288.631   3616   860    22   733674.402  4.608768e+05
2   桃園市   461974.797   62723.334   2662   945    28   528333.131  3.250724e+05
3   台中市   246454.775   43451.531   1629  1317    10   292862.306  1.884047e+05
7   苗栗縣   195888.627   23943.639   1191   537     9   221569.266  1.338598e+05
14  花蓮縣   178730.894   62519.391    974  1976    90   244290.285  1.831445e+05

In [29]:
df.sort_values(by=["乳牛數量", "牛乳"], ascending=False).head(10)

     縣市           牛乳          牛肉   乳牛數量  肉牛數量  用地面積           加總            熱量
8   彰化縣  2694993.796  373878.163  14704  2817    90  3086482.959  1.908314e+06
4   台南市  2069661.489  625846.666  11850  3935   120  2711413.155  1.973601e+06
12  屏東縣  1864768.812  402308.784  10666  7825    76  2285644.596  1.535848e+06
10  雲林縣  1388168.494  474524.567   7147  3702    54  1873596.061  1.405871e+06
11  嘉義縣   683429.133  114473.033   4376  1060    32   803370.166  5.134241e+05
5   高雄市   632887.771   96288.631   3616   860    22   733674.402  4.608768e+05
2   桃園市   461974.797   62723.334   2662   945    28   528333.131  3.250724e+05
3   台中市   246454.775   43451.531   1629  1317    10   292862.306  1.884047e+05
7   苗栗縣   195888.627   23943.639   1191   537     9   221569.266  1.338598e+05
14  花蓮縣   178730.894   62519.391    974  1976    90   244290.285  1.831445e+05