In [98]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
## 第一題_算閏年：

def year(num):
    if (num % 4 == 0) and ((num % 100 != 0) or (num % 400 == 0)):
        print("西元" + str(num) + "年是閏年")
    else:
        print("西元" + str(num) + "年不是閏年")

In [29]:
year(1000)

西元1000年不是閏年

In [30]:
year(1200)

西元1200年是閏年

# 第二題_請實作五乘五矩陣的矩陣加法函式：

In [73]:
def matrix_plus(m1, m2):
    if m1.shape == (5,5) and m2.shape == (5,5):
        print(m1+m2)
    else:
        print("error")

In [83]:
matrix_plus(np.random.rand(5,5), np.random.rand(5,5))

[[0.90359161 1.27524892 0.81459167 1.17577028 0.95648572]
 [1.72259394 0.89243647 1.27883685 1.46550012 1.40264746]
 [1.07905152 1.83029782 1.00235202 1.26688447 0.28200145]
 [1.46895665 0.86046273 0.67979227 1.0463213  0.78601985]
 [0.56523542 0.96164822 1.20469281 1.28044931 0.41679289]]

# 第三題_錄取分數表格

In [90]:
科目 = ["國文", "英文", "數甲", "數乙", "物理", "化學", "生物", "歷史", "地理", "公民"]
分數 = [86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]
weights = {
"土語系": [2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
"財政系": [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
"金融系": [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
"國貿系": [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
"會計系": [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
"法律系": [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
"公行系": [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
"應數系": [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
"教育系": [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]
}

In [95]:
grade = pd.DataFrame(weights.values(), index = weights.keys(), columns = 科目)

In [ ]:
grade["加權分數"] = np.dot(list(weights.values()), 分數)

In [173]:
grade

      國文   英文   數甲    數乙  物理  化學  生物  歷史  地理    公民     加權分數
土語系  2.0  2.0  0.0  1.00   0   0   0   1   1  0.00  589.200
財政系  1.0  1.5  0.0  1.50   0   0   0   0   0  0.00  350.350
金融系  1.0  1.5  0.0  2.00   0   0   0   0   0  0.00  398.600
國貿系  1.5  2.0  0.0  2.00   0   0   0   0   0  0.00  481.550
會計系  1.5  2.0  0.0  2.00   0   0   0   1   1  0.00  642.450
法律系  1.0  2.0  0.0  1.00   0   0   0   1   0  1.00  508.900
公行系  1.0  1.5  0.0  1.25   0   0   0   0   0  1.25  436.975
應數系  1.0  1.0  1.5  0.00   1   1   0   0   0  0.00  461.300
教育系  1.5  2.0  0.0  1.25   0   0   0   1   1  0.00  570.075

# 挑戰題一_Bubble Sort

In [128]:
grades = np.random.randn(100)
grades = 10*grades + 70
grades

array([61.27300426, 61.07969907, 63.91487635, 67.99623334, 73.54223318,
       74.26589481, 80.09572635, 65.17699689, 75.86113296, 84.6366434 ,
       55.28833586, 83.92286347, 57.44001742, 66.04595586, 71.45688496,
       67.54967765, 62.99810141, 61.89813706, 75.71638916, 65.78532511,
       75.56096236, 65.06458023, 50.03967828, 62.50225694, 91.29181972,
       64.79045351, 81.74826802, 69.38314546, 79.82609866, 59.93474057,
       55.91068409, 68.32087289, 80.55733723, 75.09048484, 49.71628562,
       68.57828919, 77.75856406, 61.90741173, 71.01355005, 77.55601248,
       53.49979185, 67.35151098, 67.3602854 , 66.95759615, 75.22788897,
       66.89099632, 52.02683563, 73.25807143, 44.07307615, 71.64883329,
       65.12619239, 58.53675412, 64.45542016, 73.73604524, 55.54576293,
       62.94543254, 69.90185988, 63.15555035, 82.79343002, 69.62467548,
       62.65019681, 83.54468468, 69.49541799, 69.8538625 , 75.57409246,
       69.00108193, 67.24836566, 62.42762074, 84.36153212, 70.03640491,
       90.71514307, 75.47918913, 67.48038011, 57.73505136, 73.11983957,
       67.65787189, 84.70736871, 76.80490446, 58.77601727, 54.60999348,
       61.87142676, 74.09822838, 61.38687176, 70.97706583, 69.30307738,
       74.269857  , 66.53241075, 72.71800187, 65.04268957, 68.27263156,
       69.48359462, 76.63179669, 71.52634264, 74.84740244, 79.3476512 ,
       60.64998762, 68.84991093, 78.88042112, 63.10422626, 81.11567852])

In [132]:
for i in range(len(grades)-1):
    for j in range(len(grades)-1-i):
        if grades[j] > grades[j+1]:
            mark = grades[j]
            grades[j] = grades[j+1]
            grades[j+1] = mark

In [133]:
grades

array([44.07307615, 49.71628562, 50.03967828, 52.02683563, 53.49979185,
       54.60999348, 55.28833586, 55.54576293, 55.91068409, 57.44001742,
       57.73505136, 58.53675412, 58.77601727, 59.93474057, 60.64998762,
       61.07969907, 61.27300426, 61.38687176, 61.87142676, 61.89813706,
       61.90741173, 62.42762074, 62.50225694, 62.65019681, 62.94543254,
       62.99810141, 63.10422626, 63.15555035, 63.91487635, 64.45542016,
       64.79045351, 65.04268957, 65.06458023, 65.12619239, 65.17699689,
       65.78532511, 66.04595586, 66.53241075, 66.89099632, 66.95759615,
       67.24836566, 67.35151098, 67.3602854 , 67.48038011, 67.54967765,
       67.65787189, 67.99623334, 68.27263156, 68.32087289, 68.57828919,
       68.84991093, 69.00108193, 69.30307738, 69.38314546, 69.48359462,
       69.49541799, 69.62467548, 69.8538625 , 69.90185988, 70.03640491,
       70.97706583, 71.01355005, 71.45688496, 71.52634264, 71.64883329,
       72.71800187, 73.11983957, 73.25807143, 73.54223318, 73.73604524,
       74.09822838, 74.26589481, 74.269857  , 74.84740244, 75.09048484,
       75.22788897, 75.47918913, 75.56096236, 75.57409246, 75.71638916,
       75.86113296, 76.63179669, 76.80490446, 77.55601248, 77.75856406,
       78.88042112, 79.3476512 , 79.82609866, 80.09572635, 80.55733723,
       81.11567852, 81.74826802, 82.79343002, 83.54468468, 83.92286347,
       84.36153212, 84.6366434 , 84.70736871, 90.71514307, 91.29181972])

# 挑戰題二：自己出！

### 排序台灣各縣市的乳牛數量，由多到少，再於表格增加一欄該縣市乳牛數量佔全台灣總數量之比例。

In [148]:
cow = pd.read_excel("123.xlsx")
cow

     縣市           牛乳          牛肉   乳牛數量  肉牛數量  用地面積
0   新北市   117502.880   32420.171    691   605     3
1   台北市     4956.965     299.277     34     2     0
2   桃園市   461974.797   62723.334   2662   945    28
3   台中市   246454.775   43451.531   1629  1317    10
4   台南市  2069661.489  625846.666  11850  3935   120
5   高雄市   632887.771   96288.631   3616   860    22
6   新竹縣   203520.007   27137.016    958   425    13
7   苗栗縣   195888.627   23943.639   1191   537     9
8   彰化縣  2694993.796  373878.163  14704  2817    90
9   南投縣    76767.026    3434.696    452    11     3
10  雲林縣  1388168.494  474524.567   7147  3702    54
11  嘉義縣   683429.133  114473.033   4376  1060    32
12  屏東縣  1864768.812  402308.784  10666  7825    76
13  台東縣   116156.593   49194.170    627  1522    20
14  花蓮縣   178730.894   62519.391    974  1976    90
15  新竹市    27819.861    9271.225    240    44     5
16  嘉義市     3994.825    1179.486     36     0     3
17  金門縣     6498.299   57492.006    114  5824    34

In [174]:
cow.index = cow.縣市
A = pd.DataFrame(cow.乳牛數量.sort_values(ascending=False))

In [171]:
A["乳牛比例"] = A.乳牛數量/np.sum(A.乳牛數量) * 100

In [172]:
A

      乳牛數量       乳牛比例
縣市
彰化縣  14704  23.728759
台南市  11850  19.123082
屏東縣  10666  17.212387
雲林縣   7147  11.533558
嘉義縣   4376   7.061823
高雄市   3616   5.835364
桃園市   2662   4.295835
台中市   1629   2.628819
苗栗縣   1191   1.921991
花蓮縣    974   1.571804
新竹縣    958   1.545984
新北市    691   1.115110
台東縣    627   1.011829
南投縣    452   0.729420
新竹市    240   0.387303
金門縣    114   0.183969
嘉義市     36   0.058095
台北市     34   0.054868